apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: my-first-container
  template:
    metadata:
      labels:
        name: my-first-container
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.10
          ports:
            - containerPort: 80