apiVersion: v1
kind: Pod
metadata:
  name: mysecretpod
spec:
  containers:
    - name: my-secret-nginx
      image: nginx
      volumeMounts:
        - name: mycredentials
          mountPath: "/etc/credentials"
          readOnly: true
  volumes:
    - name: mycredentials
      secret:
        secretName: mysecret