apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    name: nginx-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      name: my-first-container
  template:
    metadata:
      labels:
        name: my-first-container
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.10
          ports:
            - containerPort: 80